/**
 * UVCW Matières Configuration
 *
 * Liste des 46 matières avec leurs couleurs et pictos
 * Source: info_matieres.csv
 */

export type MatiereOrganisation = "UVCW" | "Fédé" | "UVCW/Fédé";

export interface Matiere {
  id: number;
  nom: string;
  nomCourt: string;
  slug: string;
  couleur: string; // Hex sans #
  organisation: MatiereOrganisation;
  couleurTexte: "ffffff" | "000000";
  pictoCode: string; // Code unicode pour la webfont
  pictoClass: string; // Classe CSS correspondante
}

export const MATIERES: Record<string, Matiere> = {
  "aide-alimentaire": {
    id: 634,
    nom: "Aide alimentaire",
    nomCourt: "Aide alimentaire",
    slug: "aide-alimentaire",
    couleur: "9D7847",
    organisation: "Fédé",
    couleurTexte: "ffffff",
    pictoCode: "\\e837",
    pictoClass: "picto-food",
  },
  "aide-aux-familles": {
    id: 64,
    nom: "Aide aux familles",
    nomCourt: "Aide aux familles",
    slug: "aide-aux-familles",
    couleur: "6F7AB8",
    organisation: "Fédé",
    couleurTexte: "ffffff",
    pictoCode: "\\e80a",
    pictoClass: "picto-aide-aux-familles",
  },
  "aide-sociale": {
    id: 49,
    nom: "Aide sociale",
    nomCourt: "Aide sociale",
    slug: "aide-sociale",
    couleur: "239BDB",
    organisation: "Fédé",
    couleurTexte: "ffffff",
    pictoCode: "\\e809",
    pictoClass: "picto-aide-sociale",
  },
  aines: {
    id: 52,
    nom: "Aînés",
    nomCourt: "Aînés",
    slug: "aines",
    couleur: "A31668",
    organisation: "Fédé",
    couleurTexte: "ffffff",
    pictoCode: "\\e808",
    pictoClass: "picto-aines",
  },
  "amenagement-territoire": {
    id: 4,
    nom: "Aménagement du territoire",
    nomCourt: "Aménagement du territoire",
    slug: "amenagement-territoire",
    couleur: "6F685B",
    organisation: "UVCW",
    couleurTexte: "ffffff",
    pictoCode: "\\e829",
    pictoClass: "picto-amenagement-territoire",
  },
  communication: {
    id: 5,
    nom: "Communication",
    nomCourt: "Communication",
    slug: "communication",
    couleur: "000000",
    organisation: "UVCW",
    couleurTexte: "ffffff",
    pictoCode: "\\e828",
    pictoClass: "picto-communication",
  },
  cultes: {
    id: 1070,
    nom: "Cultes/Fabriques d'églises",
    nomCourt: "Cultes / Fabriques d'églises",
    slug: "cultes",
    couleur: "A24E67",
    organisation: "UVCW",
    couleurTexte: "ffffff",
    pictoCode: "\\e827",
    pictoClass: "picto-cultes",
  },
  culture: {
    id: 1077,
    nom: "Culture",
    nomCourt: "Culture",
    slug: "culture",
    couleur: "FAB544",
    organisation: "UVCW",
    couleurTexte: "000000",
    pictoCode: "\\e826",
    pictoClass: "picto-culture",
  },
  "developpement-local": {
    id: 8,
    nom: "Développement local",
    nomCourt: "Développement local",
    slug: "developpement-local",
    couleur: "CD5975",
    organisation: "UVCW/Fédé",
    couleurTexte: "ffffff",
    pictoCode: "\\e80b",
    pictoClass: "picto-adl-developpement-local",
  },
  "propriete-intellectuelle": {
    id: 1083,
    nom: "Droit d'auteur/ Propriété intellectuelle",
    nomCourt: "Propriété intellectuelle",
    slug: "propriete-intellectuelle",
    couleur: "E09D3F",
    organisation: "UVCW",
    couleurTexte: "000000",
    pictoCode: "\\e82f",
    pictoClass: "picto-propriete-intellectuelle",
  },
  "e-gov": {
    id: 22,
    nom: "E-gov, TIC et simplification administrative",
    nomCourt: "Nouvelles technologies",
    slug: "e-gov",
    couleur: "92C4BE",
    organisation: "UVCW/Fédé",
    couleurTexte: "ffffff",
    pictoCode: "\\e824",
    pictoClass: "picto-e-gov",
  },
  "efficacite-personnelle": {
    id: 1078,
    nom: "Efficacité personnelle",
    nomCourt: "Efficacité personnelle",
    slug: "efficacite-personnelle",
    couleur: "C30071",
    organisation: "Fédé",
    couleurTexte: "ffffff",
    pictoCode: "\\e830",
    pictoClass: "picto-efficacite-personnelle",
  },
  energie: {
    id: 9,
    nom: "Energie",
    nomCourt: "Energie",
    slug: "energie",
    couleur: "AFCA0B",
    organisation: "UVCW",
    couleurTexte: "ffffff",
    pictoCode: "\\e836",
    pictoClass: "picto-energie-2",
  },
  enseignement: {
    id: 10,
    nom: "Enseignement",
    nomCourt: "Enseignement",
    slug: "enseignement",
    couleur: "812990",
    organisation: "UVCW",
    couleurTexte: "ffffff",
    pictoCode: "\\e807",
    pictoClass: "picto-enseignement",
  },
  environnement: {
    id: 11,
    nom: "Environnement",
    nomCourt: "Environnement",
    slug: "environnement",
    couleur: "13A538",
    organisation: "UVCW",
    couleurTexte: "ffffff",
    pictoCode: "\\e806",
    pictoClass: "picto-environnement",
  },
  "population-etat-civil": {
    id: 1068,
    nom: "Etat civil/Population",
    nomCourt: "Etat civil & Population",
    slug: "population-etat-civil",
    couleur: "4B6644",
    organisation: "UVCW",
    couleurTexte: "ffffff",
    pictoCode: "\\e810",
    pictoClass: "picto-population-etat-civil",
  },
  etrangers: {
    id: 54,
    nom: "Etrangers",
    nomCourt: "Etrangers",
    slug: "etrangers",
    couleur: "99A535",
    organisation: "Fédé",
    couleurTexte: "ffffff",
    pictoCode: "\\e805",
    pictoClass: "picto-etrangers",
  },
  international: {
    id: 12,
    nom: "Europe/International",
    nomCourt: "Europe/international",
    slug: "international",
    couleur: "C88396",
    organisation: "UVCW",
    couleurTexte: "ffffff",
    pictoCode: "\\e81e",
    pictoClass: "picto-europe",
  },
  finances: {
    id: 13,
    nom: "Finances et fiscalité",
    nomCourt: "Finances et fiscalité",
    slug: "finances",
    couleur: "FBBA00",
    organisation: "UVCW/Fédé",
    couleurTexte: "ffffff",
    pictoCode: "\\e804",
    pictoClass: "picto-finances",
  },
  fonctionnement: {
    id: 55,
    nom: "Fonctionnement institutionnel",
    nomCourt: "Fonctionnement",
    slug: "fonctionnement",
    couleur: "F17B5A",
    organisation: "UVCW/Fédé",
    couleurTexte: "ffffff",
    pictoCode: "\\e803",
    pictoClass: "picto-fonctionnement",
  },
  "funerailles-sepultures": {
    id: 1069,
    nom: "Funérailles et sépultures",
    nomCourt: "Funérailles et sépultures",
    slug: "funerailles-sepultures",
    couleur: "3F4E54",
    organisation: "UVCW",
    couleurTexte: "ffffff",
    pictoCode: "\\e818",
    pictoClass: "picto-funerailles-sepultures",
  },
  patrimoine: {
    id: 25,
    nom: "Gestion du patrimoine",
    nomCourt: "Gestion du patrimoine",
    slug: "patrimoine",
    couleur: "B8981A",
    organisation: "UVCW/Fédé",
    couleurTexte: "ffffff",
    pictoCode: "\\e822",
    pictoClass: "picto-patrimoine",
  },
  incendie: {
    id: 16,
    nom: "Incendie et aide médicale urgente",
    nomCourt: "Incendie",
    slug: "incendie",
    couleur: "CD1719",
    organisation: "UVCW",
    couleurTexte: "ffffff",
    pictoCode: "\\e81a",
    pictoClass: "picto-incendie",
  },
  insertion: {
    id: 50,
    nom: "Insertion socioprofessionnelle",
    nomCourt: "ISP",
    slug: "insertion",
    couleur: "E34F57",
    organisation: "Fédé",
    couleurTexte: "ffffff",
    pictoCode: "\\e81c",
    pictoClass: "picto-insertion",
  },
  intercommunalite: {
    id: 17,
    nom: "Intercommunalité/ Supracommunalité",
    nomCourt: "Inter(supra)communalité",
    slug: "intercommunalite",
    couleur: "4F80C1",
    organisation: "UVCW",
    couleurTexte: "ffffff",
    pictoCode: "\\e81d",
    pictoClass: "picto-intercommunalite",
  },
  jeunesse: {
    id: 53,
    nom: "Jeunesse et petite enfance",
    nomCourt: "Jeunesse/petite enfance",
    slug: "jeunesse",
    couleur: "9D7BC7",
    organisation: "UVCW/Fédé",
    couleurTexte: "ffffff",
    pictoCode: "\\e81f",
    pictoClass: "picto-jeunesse",
  },
  logement: {
    id: 18,
    nom: "Logement",
    nomCourt: "Logement",
    slug: "logement",
    couleur: "009BA4",
    organisation: "UVCW/Fédé",
    couleurTexte: "ffffff",
    pictoCode: "\\e802",
    pictoClass: "picto-logement",
  },
  data: {
    id: 66,
    nom: "Management de la donnée",
    nomCourt: "Management de la donnée",
    slug: "data",
    couleur: "006DA7",
    organisation: "UVCW/Fédé",
    couleurTexte: "ffffff",
    pictoCode: "\\e80c",
    pictoClass: "picto-data",
  },
  mandataires: {
    id: 19,
    nom: "Mandataires",
    nomCourt: "Mandataires",
    slug: "mandataires",
    couleur: "6A8A8A",
    organisation: "UVCW/Fédé",
    couleurTexte: "ffffff",
    pictoCode: "\\e800",
    pictoClass: "picto-mandataires",
  },
  "marches-publics": {
    id: 20,
    nom: "Marchés publics/ PPP/ Concessions",
    nomCourt: "Marchés publics",
    slug: "marches-publics",
    couleur: "661227",
    organisation: "UVCW",
    couleurTexte: "ffffff",
    pictoCode: "\\e82e",
    pictoClass: "picto-marches-publics",
  },
  "mediation-dette": {
    id: 63,
    nom: "Médiation de dettes",
    nomCourt: "Médiation de dette",
    slug: "mediation-dette",
    couleur: "DB9018",
    organisation: "Fédé",
    couleurTexte: "ffffff",
    pictoCode: "", // Pas de picto
    pictoClass: "",
  },
  "methodologie-travail-social": {
    id: 83,
    nom: "Méthodologie en travail social",
    nomCourt: "Méthodologie en travail social",
    slug: "methodologie-travail-social",
    couleur: "B6AAD1",
    organisation: "Fédé",
    couleurTexte: "ffffff",
    pictoCode: "\\e831",
    pictoClass: "picto-methodologie-travail-social",
  },
  mobilite: {
    id: 21,
    nom: "Mobilité",
    nomCourt: "Mobilité",
    slug: "mobilite",
    couleur: "66B2E4",
    organisation: "UVCW",
    couleurTexte: "ffffff",
    pictoCode: "\\e82d",
    pictoClass: "picto-mobilite",
  },
  paralocaux: {
    id: 23,
    nom: "Paralocaux, régies, associations",
    nomCourt: "Paralocaux, régies, asbl",
    slug: "paralocaux",
    couleur: "1E6EA6",
    organisation: "UVCW",
    couleurTexte: "ffffff",
    pictoCode: "\\e82c",
    pictoClass: "picto-paralocaux",
  },
  "participation-citoyenne": {
    id: 24,
    nom: "Participation citoyenne",
    nomCourt: "Participation citoyenne",
    slug: "participation-citoyenne",
    couleur: "F0C728",
    organisation: "UVCW/Fédé",
    couleurTexte: "ffffff",
    pictoCode: "\\e82b",
    pictoClass: "picto-participation-citoyenne",
  },
  pauvrete: {
    id: 51,
    nom: "Pauvreté",
    nomCourt: "Pauvreté",
    slug: "pauvrete",
    couleur: "942431",
    organisation: "Fédé",
    couleurTexte: "ffffff",
    pictoCode: "\\e821",
    pictoClass: "picto-pauvrete",
  },
  personnel: {
    id: 26,
    nom: "Personnel/RH",
    nomCourt: "Personnel/RH",
    slug: "personnel",
    couleur: "DA570F",
    organisation: "UVCW/Fédé",
    couleurTexte: "ffffff",
    pictoCode: "\\e80d",
    pictoClass: "picto-personnel",
  },
  "police-administrative": {
    id: 59,
    nom: "Police administrative et ordre public",
    nomCourt: "Police administrative",
    slug: "police-administrative",
    couleur: "82368C",
    organisation: "UVCW",
    couleurTexte: "ffffff",
    pictoCode: "\\e80e",
    pictoClass: "picto-police-administrative",
  },
  "police-locale": {
    id: 27,
    nom: "Police locale",
    nomCourt: "Police locale",
    slug: "police-locale",
    couleur: "283583",
    organisation: "UVCW",
    couleurTexte: "ffffff",
    pictoCode: "\\e80f",
    pictoClass: "picto-police",
  },
  ville: {
    id: 1450,
    nom: "Politique de la Ville",
    nomCourt: "Politique de la Ville",
    slug: "ville",
    couleur: "4762B2",
    organisation: "UVCW",
    couleurTexte: "ffffff",
    pictoCode: "\\e832",
    pictoClass: "picto-ville",
  },
  ruralite: {
    id: 29,
    nom: "Ruralité",
    nomCourt: "Ruralité",
    slug: "ruralite",
    couleur: "B76E11",
    organisation: "UVCW",
    couleurTexte: "ffffff",
    pictoCode: "\\e833",
    pictoClass: "picto-ruralite-ville",
  },
  sante: {
    id: 30,
    nom: "Santé",
    nomCourt: "Santé",
    slug: "sante",
    couleur: "596F91",
    organisation: "Fédé",
    couleurTexte: "ffffff",
    pictoCode: "\\e812",
    pictoClass: "picto-sante",
  },
  "sociale-energie": {
    id: 1537,
    nom: "Sociale énergie",
    nomCourt: "Sociale énergie",
    slug: "sociale-energie",
    couleur: "AFCA0B",
    organisation: "Fédé",
    couleurTexte: "ffffff",
    pictoCode: "\\e823",
    pictoClass: "picto-energie",
  },
  "sport-loisirs": {
    id: 1075,
    nom: "Sport/loisirs",
    nomCourt: "Sport & loisirs",
    slug: "sport-loisirs",
    couleur: "FAB544",
    organisation: "UVCW",
    couleurTexte: "000000",
    pictoCode: "\\e813",
    pictoClass: "picto-sport-loisirs",
  },
  "strategie-management": {
    id: 14,
    nom: "Stratégie/Management",
    nomCourt: "Stratégie/Management",
    slug: "strategie-management",
    couleur: "41728F",
    organisation: "UVCW/Fédé",
    couleurTexte: "ffffff",
    pictoCode: "\\e801",
    pictoClass: "picto-strategie-management",
  },
  voirie: {
    id: 1058,
    nom: "Voirie et travaux",
    nomCourt: "Voirie/travaux",
    slug: "voirie",
    couleur: "65B2E4",
    organisation: "UVCW",
    couleurTexte: "ffffff",
    pictoCode: "\\e815",
    pictoClass: "picto-voirie",
  },
};

// Helper pour obtenir une matière par slug
export const getMatiere = (slug: string): Matiere | undefined => {
  return MATIERES[slug];
};

// Helper pour obtenir la couleur avec #
export const getMatiereColor = (slug: string): string => {
  const matiere = MATIERES[slug];
  return matiere ? `#${matiere.couleur}` : "#6B7280";
};

// Liste des slugs pour l'autocomplétion
export type MatiereSlug = keyof typeof MATIERES;
